http:
  port: 8011
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

db:
  hostname: localhost
  name: laravel
  port: 3306
  username: sail
  password: password

kafka:
  kafka_host: kafka
  kafka_port: 9092

api_token: S9QmPxwWXnLW53RDDqpFqsf8RtBViBGiIRjzQtVIXqFS